function changeSizeSmall() {
  changeSize(HTML_CLASS_CONST.RCALC_BUTTON, HTML_CSS_CONST.FONT_SIZE_SMALL_20_PX, HTML_CSS_CONST.WIDTH_SMALL_30_PX, HTML_CSS_CONST.HEIGHT_SMALL_30_PX);
  changeSize(HTML_CLASS_CONST.RCALC_BUTTON_OPERATOR, HTML_CSS_CONST.FONT_SIZE_SMALL_20_PX, HTML_CSS_CONST.WIDTH_SMALL_30_PX, HTML_CSS_CONST.HEIGHT_SMALL_30_PX);
  changeSize(HTML_CLASS_CONST.RCALC_BUTTON_CLEAR, HTML_CSS_CONST.FONT_SIZE_SMALL_20_PX, HTML_CSS_CONST.WIDTH_SMALL_30_PX, HTML_CSS_CONST.HEIGHT_SMALL_30_PX);
  changeSize(HTML_CLASS_CONST.RCALC_DISPLAY_MAIN, HTML_CSS_CONST.FONT_SIZE_SMALL_20_PX, HTML_CSS_CONST.WIDTH_SMALL_93_PX, HTML_CSS_CONST.HEIGHT_SMALL_25_PX);
  changeSize(HTML_CLASS_CONST.RCALC_DISPLAY_INFO, HTML_CSS_CONST.FONT_SIZE_SMALL_8_PX, HTML_CSS_CONST.WIDTH_SMALL_125_PX, HTML_CSS_CONST.HEIGHT_SMALL_25_PX);
}

function changeSizeDefault() {
  changeSize(HTML_CLASS_CONST.RCALC_BUTTON, HTML_CSS_CONST.FONT_SIZE_DEFAULT_40_PX, HTML_CSS_CONST.WIDTH_DEFAULT_60_PX, HTML_CSS_CONST.HEIGHT_DEFAULT_60_PX);
  changeSize(HTML_CLASS_CONST.RCALC_BUTTON_OPERATOR, HTML_CSS_CONST.FONT_SIZE_DEFAULT_40_PX, HTML_CSS_CONST.WIDTH_DEFAULT_60_PX, HTML_CSS_CONST.HEIGHT_DEFAULT_60_PX);
  changeSize(HTML_CLASS_CONST.RCALC_BUTTON_CLEAR, HTML_CSS_CONST.FONT_SIZE_DEFAULT_40_PX, HTML_CSS_CONST.WIDTH_DEFAULT_60_PX, HTML_CSS_CONST.HEIGHT_DEFAULT_60_PX);
  changeSize(HTML_CLASS_CONST.RCALC_DISPLAY_MAIN, HTML_CSS_CONST.FONT_SIZE_DEFAULT_40_PX, HTML_CSS_CONST.WIDTH_DEFAULT_186_PX, HTML_CSS_CONST.HEIGHT_DEFAULT_55_PX);
  changeSize(HTML_CLASS_CONST.RCALC_DISPLAY_INFO, HTML_CSS_CONST.FONT_SIZE_DEFAULT_17_PX, HTML_CSS_CONST.WIDTH_DEFAULT_250_PX, HTML_CSS_CONST.HEIGHT_DEFAULT_55_PX);
}

function changeSizeLarge() {
  changeSize(HTML_CLASS_CONST.RCALC_BUTTON, HTML_CSS_CONST.FONT_SIZE_LARGE_70_PX, HTML_CSS_CONST.WIDTH_LARGE_100_PX, HTML_CSS_CONST.HEIGHT_LARGE_100_PX);
  changeSize(HTML_CLASS_CONST.RCALC_BUTTON_OPERATOR, HTML_CSS_CONST.FONT_SIZE_LARGE_70_PX, HTML_CSS_CONST.WIDTH_LARGE_100_PX, HTML_CSS_CONST.HEIGHT_LARGE_100_PX);
  changeSize(HTML_CLASS_CONST.RCALC_BUTTON_CLEAR, HTML_CSS_CONST.FONT_SIZE_LARGE_70_PX, HTML_CSS_CONST.WIDTH_LARGE_100_PX, HTML_CSS_CONST.HEIGHT_LARGE_100_PX);
  changeSize(HTML_CLASS_CONST.RCALC_DISPLAY_MAIN, HTML_CSS_CONST.FONT_SIZE_LARGE_70_PX, HTML_CSS_CONST.WIDTH_LARGE_305_PX, HTML_CSS_CONST.HEIGHT_LARGE_100_PX);
  changeSize(HTML_CLASS_CONST.RCALC_DISPLAY_INFO, HTML_CSS_CONST.FONT_SIZE_LARGE_30_PX, HTML_CSS_CONST.WIDTH_LARGE_410_PX, HTML_CSS_CONST.HEIGHT_LARGE_100_PX);
}

function changeSize(rcalcCssClass, fontSize, width, height) {
  var buttonsDisplays = document.getElementsByClassName(rcalcCssClass);
  for (var i = 0; i < buttonsDisplays.length; i++) {
    buttonsDisplays[i].style.fontSize = addSuffixPx(fontSize);
    buttonsDisplays[i].style.width = addSuffixPx(width);
    buttonsDisplays[i].style.height = addSuffixPx(height);
  }
}

function addSuffixPx(size) {
  return size + STRING_UTILITY_CONST.SUFFIX_PX;
}