function changeSizeSmall() {
  changeSize(RCALC_BUTTON, FONT_SIZE_SMALL_20_PX, WIDTH_SMALL_30_PX, HEIGHT_SMALL_30_PX);
  changeSize(RCALC_BUTTON_OPERATOR, FONT_SIZE_SMALL_20_PX, WIDTH_SMALL_30_PX, HEIGHT_SMALL_30_PX);
  changeSize(RCALC_BUTTON_CLEAR, FONT_SIZE_SMALL_20_PX, WIDTH_SMALL_30_PX, HEIGHT_SMALL_30_PX);
  changeSize(RCALC_DISPLAY_MAIN, FONT_SIZE_SMALL_20_PX, WIDTH_SMALL_93_PX, HEIGHT_SMALL_25_PX);
  changeSize(RCALC_DISPLAY_INFO, FONT_SIZE_SMALL_8_PX, WIDTH_SMALL_125_PX, HEIGHT_SMALL_25_PX);
}

function changeSizeDefault() {
  changeSize(RCALC_BUTTON, FONT_SIZE_DEFAULT_40_PX, WIDTH_DEFAULT_60_PX, HEIGHT_DEFAULT_60_PX);
  changeSize(RCALC_BUTTON_OPERATOR, FONT_SIZE_DEFAULT_40_PX, WIDTH_DEFAULT_60_PX, HEIGHT_DEFAULT_60_PX);
  changeSize(RCALC_BUTTON_CLEAR, FONT_SIZE_DEFAULT_40_PX, WIDTH_DEFAULT_60_PX, HEIGHT_DEFAULT_60_PX);
  changeSize(RCALC_DISPLAY_MAIN, FONT_SIZE_DEFAULT_40_PX, WIDTH_DEFAULT_186_PX, HEIGHT_DEFAULT_55_PX);
  changeSize(RCALC_DISPLAY_INFO, FONT_SIZE_DEFAULT_17_PX, WIDTH_DEFAULT_250_PX, HEIGHT_DEFAULT_55_PX);
}

function changeSizeLarge() {
  changeSize(RCALC_BUTTON, FONT_SIZE_LARGE_70_PX, WIDTH_LARGE_100_PX, HEIGHT_LARGE_100_PX);
  changeSize(RCALC_BUTTON_OPERATOR, FONT_SIZE_LARGE_70_PX, WIDTH_LARGE_100_PX, HEIGHT_LARGE_100_PX);
  changeSize(RCALC_BUTTON_CLEAR, FONT_SIZE_LARGE_70_PX, WIDTH_LARGE_100_PX, HEIGHT_LARGE_100_PX);
  changeSize(RCALC_DISPLAY_MAIN, FONT_SIZE_LARGE_70_PX, WIDTH_LARGE_305_PX, HEIGHT_LARGE_100_PX);
  changeSize(RCALC_DISPLAY_INFO, FONT_SIZE_LARGE_30_PX, WIDTH_LARGE_410_PX, HEIGHT_LARGE_100_PX);
}

function changeSize(rcalcCssClass, fontSize, width, height) {
  var buttonsDisplays = document.getElementsByClassName(rcalcCssClass);
  for (var i = 0; i < buttonsDisplays.length; i++) {
    buttonsDisplays[i].style.fontSize = addSuffixPx(fontSize);
    buttonsDisplays[i].style.width = addSuffixPx(width);
    buttonsDisplays[i].style.height = addSuffixPx(height);
  }
}

function addSuffixPx(size) {
  return size + SUFFIX_PX;
}